### ISSUE TITLE
Does not work with bluetooth_proxy/esp32_ble_tracker

### ISSUE THREAD

**Issue by shep89** [shammysha/esphome-mi-remote#6]
Looks like ble_mi_remote incompatible with esp32_ble_tracker or bluetooth_proxy

```yaml
ble_mi_remote:
  id: mi_remote
  name: "MI Remote"
  manufacturer_id: "Shammysha"
  battery_level: 100 
  reconnect: true # auto reconnect after reboot
```

This config on my device works if present exclusively.

If i add any of following integrations
```yaml
esp32_ble_tracker:
```
or
```yaml
bluetooth_proxy:
```
ble_mi_remote stops working and esp32_ble_tracker/bluetooth_proxy working fine same time.
